FROM python:3.10-slim

WORKDIR /app

# Copy everything inside the commander folder into /app/commander inside the image
COPY commander/ /app/commander/
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENV PYTHONUNBUFFERED=1
ENV REDIS_HOST=redis
ENV RABBIT_HOST=rabbitmq
ENV RABBIT_PORT=5672

# Run the FastAPI app
CMD ["uvicorn", "commander.main:app", "--host", "0.0.0.0", "--port", "8000"]
